install.packages("systemfonts")
install.packages("R.utils")
install.packages("dplyr")
install.packages("tidyr")
install.packages("data.table")
install.packages("RColorBrewer")
install.packages("gplots")
install.packages("reshape2")
install.packages("Polychrome")
install.packages("dendextend")
install.packages("ggplot2")
install.packages("dynamicTreeCut")
install.packages("qdapTools")
install.packages("hrbrthemes")
install.packages("tibble")
install.packages("caret")
install.packages("ggplot2")
install.packages("tools")
install.packages("igraph")
install.packages("rmarkdown")
install.packages("knitr")
install.packages("kableExtra")

install.packages("hrbrthemes")

packageurl <- "https://cran.r-project.org/src/contrib/Archive/rvcheck/rvcheck_0.1.8.tar.gz"
install.packages(packageurl, repos=NULL, type="source")

install.packages("BiocManager")
BiocManager::install("clusterProfiler")
BiocManager::install("edgeR")
BiocManager::install("DESeq2")
BiocManager::install("biomaRt")
